spring:
  application:
    name: notifaction-service
  profiles:
    active: local
  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

server:
  port: 8082

gateway:
  auth:
    secret: ${JWT_SECRET}

