spring:
  application:
    name: booking-service
  profiles:
    active: local
  liquibase:
    enabled: false
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

server:
  port: 8081

gateway:
  auth:
    secret: ${JWT_SECRET}

room-service:
  url: http://localhost:8083

notification-service:
  url: http://localhost:8082

kafka:
  topic:
    booking-notifications: booking-notifications