spring:
  application:
    name: booking-service
  profiles:
    active: local
  liquibase:
    enabled: false

server:
  port: 8081

gateway:
  auth:
    secret: ${JWT_SECRET}

room-service:
  url: http://localhost:8083

notification-service:
  url: http://localhost:8082